name: Xcode - Build and Analyze

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo $default > default
          echo Using default scheme: $default
      - name: Build
        env:
          scheme: ${{ github.event.repository.default_branch }}
        run: |
          if [ "$scheme" = "default" ]; then scheme=$(cat default); fi
          if [ -n "$(find . -name '*.xcworkspace' -type d 2>/dev/null)" ]; then 
            filetype_parameter="workspace" 
            file_to_build="$(find . -name '*.xcworkspace' -type d | head -n 1)"
          else 
            filetype_parameter="project" 
            file_to_build="$(find . -name '*.xcodeproj' -type d | head -n 1)"
          fi
          file_to_build=$(basename "$file_to_build")
          echo "Building $filetype_parameter: $file_to_build with scheme: $scheme"
          xcodebuild clean build analyze -scheme "$scheme" -"$filetype_parameter" "$file_to_build" | xcpretty && exit ${PIPESTATUS[0]}
