name: Xcode - Build and Analyze

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build and analyse Xcode project/workspace
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode Version
        run: |
          # リポジトリを作成/保存したXcodeのバージョンに合わせて、以下のパスを修正してください。
          # 例: Xcode 15.3 なら /Applications/Xcode_15.3.app
          TARGET_XCODE_PATH="/Applications/Xcode_16.3.app" # ここを適切なパスに修正！

          if [ -d "$TARGET_XCODE_PATH" ]; then
            echo "Selecting Xcode at $TARGET_XCODE_PATH"
            sudo xcode-select -s "$TARGET_XCODE_PATH"
            xcode-select --print-path
            xcodebuild -version
          else
            echo "Error: Xcode path $TARGET_XCODE_PATH does not exist on the runner."
            echo "Available Xcode applications:"
            ls /Applications/Xcode*.app
            exit 1
          fi

      - name: Build and Analyze
        run: bash .github/scripts/build_and_analyze.sh
